#library(devtools)
#install_github("kassambara/factoextra")


r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("ggcorrplot")
install.packages("patchwork")
install.packages("caret")
install.packages("ggthemes")
install.packages("Metrics")
install.packages("GGally")
install.packages("shiny")
install.packages("kableExtra")
install.packages("plotly")
install.packages("rpart.plot")

library(rpart.plot)
library(rpart)
library(plotly)
library(kableExtra)
library(tidyverse)
library(ggplot2)
library(ggcorrplot)
library(patchwork)
library(caret)
library(ggthemes)
library(Metrics)
library(GGally)
library(gbm)
library(shiny)
library(factoextra)
library(lubridate)

